name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.81.38.192 'cd /home/ubuntu/react-native-notes-app/ && git pull origin main && npm install && pm2 restart all'
        sudo apt-get install awscli -y
        aws s3 cp s3://gitops/deployment.zip .
        unzip deployment.zip
        cd deployment
        npm install
        npm run build
        pm2 start server.js
