name: CI-CD_Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Install Node.js and npm
          curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
          # Install PM2
          sudo npm install -g pm2
          
          # Clone the repository if it does not exist
          if [ ! -d "/home/ubuntu/react-native-notes-app" ]; then
            git clone https://github.com/KrishVarma69/react-native-notes-app.git /home/ubuntu/react-native-notes-app
          fi
          
          # Navigate to the project directory
          cd /home/ubuntu/react-native-notes-app/
          
          # Pull the latest changes
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Build the project
          npm run build
          
          # Restart the application using PM2
          pm2 restart app
        port: 22
        sync: false
        use_insecure_cipher: false
        timeout: 30s
        command_timeout: 10m
        proxy_port: 22
        proxy_timeout: 30s
        proxy_use_insecure_cipher: false
        script_stop: false
        debug: false
